; =============================================================================
;  AutoIt BinaryCall UDF Demo
;  Author: Ward
; =============================================================================

#Include "..\BinaryCall.au3"

; Scripts generated by BinaryCall Tool without modification

If @AutoItX64 Then
	Local $Code = 'AwAAAATGAAAAAAAAAAAkL48ClEDNZI5RGY5Tkc2cF56a1diYFk5KHiEqQ9+hg06ERJEBY9kWrFTGQxCSlJMtOW3Ztf5B5eAQY591h2eh+l+SRB4zDPxHAVbkM1qxqZW6eoQgmD3LzJ8OP8DaAA=='
	Local $Reloc = 'AwAAAAQEAAAAAAAAAAABABaZXz8AAA=='
	Local $Symbol[] = ["main"]

	Local $CodeBase = _BinaryCall_Create($Code, $Reloc)
	If @Error Then Exit MsgBox(16, "_BinaryCall_Create Error", _BinaryCall_LastError())
	Local $SymbolList = _BinaryCall_SymbolList($CodeBase, $Symbol)
	If @Error Then Exit MsgBox(16, "_BinaryCall_SymbolList Error", _BinaryCall_LastError())
EndIf

If Not @AutoItX64 Then
	Local $Code = 'AwAAAATcAAAAAAAAAABcQfD56Bcn8lI3g9iUaiB8k8KxbaUwkp90v5gBC0db2xEku41xSvxVNjMKsQQqMcHLd+TV7GifKqdTwfEMJY1fG6LT360U9LTVIQjsuHP5F2k81tj9yFJ+OcwDTcW7i2rfmg6YIZdMpNF+428Ujt4A'
	Local $Reloc = 'AwAAAAQGAAAAAAAAAAABABoKVy/STgAA'
	Local $Symbol[] = ["main"]

	Local $CodeBase = _BinaryCall_Create($Code, $Reloc)
	If @Error Then Exit MsgBox(16, "_BinaryCall_Create Error", _BinaryCall_LastError())
	Local $SymbolList = _BinaryCall_SymbolList($CodeBase, $Symbol)
	If @Error Then Exit MsgBox(16, "_BinaryCall_SymbolList Error", _BinaryCall_LastError())
EndIf


DllCallAddress("none:cdecl", DllStructGetData($SymbolList, "main"))
